{{- if .Values.imagePullSecret }}
{{- $registryAuthDocument := dict -}}
{{- $_ := set $registryAuthDocument "username" .Values.imagePullSecret.username }}
{{- $_ := set $registryAuthDocument "password" .Values.imagePullSecret.password }}
{{- $authMessage := printf "%s:%s" $registryAuthDocument.username $registryAuthDocument.password | b64enc }}
{{- $_ := set $registryAuthDocument "auth" $authMessage }}
{{- $dockerAuthDocument := dict .Values.imagePullSecret.registryURL $registryAuthDocument }}
{{- $dockerConfigJSONDocument := dict "auths" $dockerAuthDocument -}}
---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
data:
  .dockerconfigjson: {{ $dockerConfigJSONDocument | toJson | b64enc | quote }}
type: "kubernetes.io/dockerconfigjson"
...
{{- end }}