---
apiVersion: "v1"
kind: "Secret"
type: "Opaque"
metadata:
  name: {{ include "common.names.fullname" . }}-env
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
stringData:
  DATABASE_USER: {{ .Values.database.user | quote }}
  DATABASE_PASSWORD: {{ .Values.database.pass | quote }}
  DATABASE_NAME: {{ .Values.database.name | quote }}
  DATABASE_SERVER: {{ .Values.database.host | quote }}
  DATABASE_PORT: {{ .Values.database.port | quote }}
  JAEGER_ENDPOINT: {{ .Values.tracing.endpoint | quote }}
  SMTP_USER: {{ .Values.smtp.user | quote }}
  SMTP_PASS: {{ .Values.smtp.pass | quote }}
  SMTP_SERVER: {{ .Values.smtp.host | quote }}
  SMTP_PORT: {{ .Values.smtp.user | quote }}
  ORDER_BACKEND: {{ .Values.backend.order | quote }}
  VIDEO_BACKEND: {{ .Values.backend.video | quote }}
---
apiVersion: "v1"
kind: "Secret"
type: "Opaque"
metadata:
  name: {{ include "common.names.fullname" . }}-files
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  serviceAccountKey.json: {{ .Files.Get "files/serviceAccountKey.json" | b64enc }}
---
{{- if and (.Values.ingress.enabled) (not .Values.ingress.tls.secretName) }}
apiVersion: "v1"
kind: "Secret"
type: "tls"
metadata:
  name: {{ include "common.names.fullname" . }}-tls
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  tls.crt: {{ .Files.Get "files/tls.crt" | b64enc }}
  tls.key: {{ .Files.Get "files/tls.key" | b64enc }}
{{- end }}
...